security:
  basic:
    enabled: false
management:
  security:
    enabled: false
server:
  port: 8080
spring: 
  cloud:
    config:
      server:
        git:
          uri: http://gogs-ci-cd.cloudapps.tim.com.pe/gogs/conf
