security:
  basic:
    enabled: false
management:
  security:
    enabled: false
server:
  port: ${PORT:3333}
spring: 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cruizg/conf