node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git credentialsId: 'JenkinUser', url: 'https://steps.everis.com/git/ACELMOBILE/microservices-cuenta-prepago.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
   }
   stage('stopcontainer'){
       def rest = sh(script: 'docker ps -a -q --filter name=microservices-cuenta-prepago', returnStdout: true)
        if (rest != '') {
            sh 'docker stop $(docker ps -a -q --filter name=microservices-cuenta-prepago)'
        }else{
            echo 'No se encuentra contenedor'
        }
        
   }
   stage('removecontainer'){
       def rest = sh(script: 'docker ps -a -q --filter name=microservices-cuenta-prepago', returnStdout: true)
        if (rest != '') {
            sh 'docker rm $(docker ps -a -q --filter name=microservices-cuenta-prepago)'
        }else{
            echo 'No se encuentra contenedor'
        }
       
   }
   stage('removeimage'){
       def rest = sh(script: 'docker image ls -q --filter reference=microservices-cuenta-prepago', returnStdout: true)
        if (rest != '') {
            //sh 'docker rmi -f $(docker image ls -q --filter "reference=microservices-cuenta-prepago")'
        }else{
            echo 'No se encuentra imagen'
        }
       
       
   }
   stage('moverproperties'){
       def exists = fileExists 'application.yml'
       if (exists) {
       sh 'mv application.yml /filesapp/microservicios/prepago/properties/.' 
       echo 'ok'
       }else{
       echo 'No se encuentra archivo YAML'       
       }
       
   }
   stage('Build') {
      // Run the maven build
      if (isUnix()) {
        sh 'docker build -t microservices-cuenta-prepago microservices-cuenta-prepago/.'
          
        }
       
   }
   stage('deploycontainer'){
       sh 'docker run -d --name microservices-cuenta-prepago -v /filesapp/microservicios/prepago/:/filesapp/microservicios/prepago/:rw -p 8080:8080 microservices-cuenta-prepago'
   }
   
    
}