apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: salesorderapi
  name: salesorderapi
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: azpent/salesorderapi
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
