apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: serverturbine
  name: serverturbine
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: azpent/serverturbine
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
