apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: serverconfig
  name: serverconfig
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: azpent/serverconfig
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
